--- 
- name: webservers
  hosts: [webservers]
  remote_user: student
  become: yes
  become_method: sudo
  roles:
    - nginx-web
    
- name:  loadbalancer
  hosts: [lbservers]
  remote_user: student
  become: yes
  become_method: sudo

  roles:
    - nginx-web
    - nginx-lb

goit
   